# Generated by Django 2.1.4 on 2019-03-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_borgwardenginediagnostics_tboxdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineDiagnosticsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=255, null=True)),
                ('vin', models.CharField(blank=True, max_length=255, null=True)),
                ('engine', models.CharField(blank=True, max_length=255, null=True)),
                ('fault_code', models.CharField(blank=True, max_length=255, null=True)),
                ('fault_phenomenon', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'engine_diagnostics_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EngineFaultCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_code', models.CharField(blank=True, max_length=255, null=True)),
                ('interpretation', models.CharField(blank=True, max_length=255, null=True)),
                ('fault_cause', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnostic_scheme', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'engine_fault_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EngineFaultPhenomenon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_phenomenon', models.CharField(blank=True, max_length=255, null=True)),
                ('fault_cause', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnostic_scheme', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'engine_fault_phenomenon',
                'managed': False,
            },
        ),
    ]
